{{- if .Values.aiExtension.enabled }}
apiVersion: ai-platform.suse.com/v1alpha1
kind: InstallAIExtension
metadata:
  name: {{ .Values.aiExtension.extension.name }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
spec:
  source:
    kind: {{ .Values.aiExtension.source.kind }}
    {{- if eq .Values.aiExtension.source.kind "Helm" }}
    helm:
      chartURL: {{ .Values.aiExtension.source.helm.chartURL | quote }}
      version: {{ .Values.aiExtension.source.helm.version | quote }}
    {{- end }}
  extension:
    name: {{ .Values.aiExtension.extension.name | quote }}
    version: {{ .Values.aiExtension.extension.version | quote }}
{{- end }}
