apiVersion: ai-platform.suse.com/v1alpha1
kind: InstallAIExtension
metadata:
  name: suseai
spec:
  helm:
    name: aif-ui
    url: "oci://ghcr.io/leooamaral/charts/aif-ui"
    version: "0.1.0"
  extension:
    name: aif-ui
    version: "0.1.0"