replicaCount: 1

global:
  imageRegistry: ""
  imagePullSecrets: []

image:
  registry: ghcr.io
  repository: suse/aif-ui
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

probes:
  liveness:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%
