apiVersion: v1
kind: Service
metadata:
  name: {{ include "aif-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    {{- include "aif-operator.selectorLabels" . | nindent 4 }}
